import json

path = "/home/habb/Kuliah/sdn-iot/Reinforcement Learning/revision/allModel.ipynb"
with open(path, "r") as f:
    nb = json.load(f)

# The new training cell
training_cell_source = [
    "# --- 1. Inisialisasi Model RL dan Optimizer ---\n",
    "import torch.optim as optim\n",
    "\n",
    "state_dim = INPUT_DIM\n",
    "action_dim_discrete = 3  # 0: Maintain, 1: Increase, 2: Decrease\n",
    "action_dim_continuous = 1 # Persentase perubahan rate\n",
    "\n",
    "# DQN & DDQN\n",
    "dqn_model = DQN(state_dim, action_dim_discrete).to(DEVICE)\n",
    "dqn_target = DQN(state_dim, action_dim_discrete).to(DEVICE)\n",
    "dqn_target.load_state_dict(dqn_model.state_dict())\n",
    "dqn_opt = optim.Adam(dqn_model.parameters(), lr=1e-3)\n",
    "\n",
    "ddqn_model = DuelingDQN(state_dim, action_dim_discrete).to(DEVICE)\n",
    "ddqn_target = DuelingDQN(state_dim, action_dim_discrete).to(DEVICE)\n",
    "ddqn_target.load_state_dict(ddqn_model.state_dict())\n",
    "ddqn_opt = optim.Adam(ddqn_model.parameters(), lr=1e-3)\n",
    "\n",
    "# PPO Standard\n",
    "ppo_model = ActorCritic(state_dim, action_dim_continuous).to(DEVICE)\n",
    "ppo_opt = optim.Adam(ppo_model.parameters(), lr=3e-4)\n",
    "\n",
    "# Proposed SDH-PPO\n",
    "sdh_actor = PPOActor(state_dim).to(DEVICE)\n",
    "sdh_critic = DuelingCritic(state_dim).to(DEVICE)\n",
    "sdh_actor_opt = optim.Adam(sdh_actor.parameters(), lr=3e-4)\n",
    "sdh_critic_opt = optim.Adam(sdh_critic.parameters(), lr=3e-4)\n",
    "\n",
    "# --- 2. Real Offline Training Loop ---\n",
    "epochs = 500  # Menggunakan 500 epoch untuk training di dalam notebook\n",
    "batch_size = 64\n",
    "gamma = 0.99\n",
    "\n",
    "training_results = {\n",
    "    'Proposed (SDH-PPO)': {'loss': [], 'reward': []},\n",
    "    'PPO Standard': {'loss': [], 'reward': []},\n",
    "    'DQN': {'loss': [], 'reward': []},\n",
    "    'DDQN': {'loss': [], 'reward': []}\n",
    "}\n",
    "\n",
    "print(\"Memulai Real Offline Training (Behavioral Cloning + TD Learning) untuk Model RL...\")\n",
    "for epoch in range(epochs):\n",
    "    # Sample mini-batch dari train_df\n",
    "    batch = train_df.sample(batch_size)\n",
    "    \n",
    "    # Konversi ke Tensor PyTorch\n",
    "    states = torch.tensor(np.stack(batch['state'].values), dtype=torch.float32).to(DEVICE)\n",
    "    next_states = torch.tensor(np.stack(batch['next_state'].values), dtype=torch.float32).to(DEVICE)\n",
    "    rewards = torch.tensor(batch['reward'].values, dtype=torch.float32).unsqueeze(1).to(DEVICE)\n",
    "    actions_discrete = torch.tensor(batch['action_discrete'].values, dtype=torch.long).unsqueeze(1).to(DEVICE)\n",
    "    actions_continuous = torch.tensor(batch['action_continuous'].values, dtype=torch.float32).unsqueeze(1).to(DEVICE)\n",
    "    # Asumsi tidak ada terminal state di dataset statis IoT kita\n",
    "    dones = torch.zeros((batch_size, 1), dtype=torch.float32).to(DEVICE)\n",
    "\n",
    "    # --- DQN Update ---\n",
    "    q_values = dqn_model(states).gather(1, actions_discrete)\n",
    "    next_q_values = dqn_target(next_states).max(1)[0].unsqueeze(1).detach()\n",
    "    target_q = rewards + gamma * next_q_values * (1 - dones)\n",
    "    loss_dqn = nn.MSELoss()(q_values, target_q)\n",
    "    \n",
    "    dqn_opt.zero_grad(); loss_dqn.backward(); dqn_opt.step()\n",
    "    if epoch % 10 == 0: dqn_target.load_state_dict(dqn_model.state_dict())\n",
    "        \n",
    "    training_results['DQN']['loss'].append(loss_dqn.item())\n",
    "    training_results['DQN']['reward'].append(rewards.mean().item())\n",
    "\n",
    "    # --- DDQN Update ---\n",
    "    q_values_ddqn = ddqn_model(states).gather(1, actions_discrete)\n",
    "    next_actions = ddqn_model(next_states).max(1)[1].unsqueeze(1)\n",
    "    next_q_values_ddqn = ddqn_target(next_states).gather(1, next_actions).detach()\n",
    "    target_q_ddqn = rewards + gamma * next_q_values_ddqn * (1 - dones)\n",
    "    loss_ddqn = nn.MSELoss()(q_values_ddqn, target_q_ddqn)\n",
    "    \n",
    "    ddqn_opt.zero_grad(); loss_ddqn.backward(); ddqn_opt.step()\n",
    "    if epoch % 10 == 0: ddqn_target.load_state_dict(ddqn_model.state_dict())\n",
    "        \n",
    "    training_results['DDQN']['loss'].append(loss_ddqn.item())\n",
    "    training_results['DDQN']['reward'].append(rewards.mean().item())\n",
    "\n",
    "    # --- PPO Standard Update (Offline BC + TD Critic) ---\n",
    "    logits_ppo, values_ppo = ppo_model(states)\n",
    "    _, next_values_ppo = ppo_model(next_states)\n",
    "    target_values_ppo = rewards + gamma * next_values_ppo.detach() * (1 - dones)\n",
    "    \n",
    "    loss_critic_ppo = nn.MSELoss()(values_ppo, target_values_ppo)\n",
    "    loss_actor_ppo = nn.MSELoss()(logits_ppo, actions_continuous) # BC (Behavioral Cloning)\n",
    "    loss_ppo = loss_critic_ppo + loss_actor_ppo\n",
    "    \n",
    "    ppo_opt.zero_grad(); loss_ppo.backward(); ppo_opt.step()\n",
    "    \n",
    "    training_results['PPO Standard']['loss'].append(loss_ppo.item())\n",
    "    training_results['PPO Standard']['reward'].append(rewards.mean().item())\n",
    "\n",
    "    # --- Proposed SDH-PPO Update ---\n",
    "    values_sdh = sdh_critic(states)\n",
    "    next_values_sdh = sdh_critic(next_states).detach()\n",
    "    target_values_sdh = rewards + gamma * next_values_sdh * (1 - dones)\n",
    "    loss_critic_sdh = nn.MSELoss()(values_sdh, target_values_sdh)\n",
    "    \n",
    "    mu_sdh, sigma_sdh = sdh_actor(states)\n",
    "    loss_actor_sdh = nn.MSELoss()(mu_sdh, actions_continuous)\n",
    "    \n",
    "    sdh_critic_opt.zero_grad(); loss_critic_sdh.backward(); sdh_critic_opt.step()\n",
    "    sdh_actor_opt.zero_grad(); loss_actor_sdh.backward(); sdh_actor_opt.step()\n",
    "    \n",
    "    training_results['Proposed (SDH-PPO)']['loss'].append((loss_critic_sdh + loss_actor_sdh).item())\n",
    "    training_results['Proposed (SDH-PPO)']['reward'].append(rewards.mean().item())\n",
    "\n",
    "print(\"Training selesai!\")\n",
    "\n",
    "# --- 3. Plotting Real Training Convergence ---\n",
    "import matplotlib.pyplot as plt\n",
    "for name in training_results:\n",
    "    plt.figure(figsize=(16, 5))\n",
    "    plt.subplot(1, 2, 1)\n",
    "    plt.plot(training_results[name]['loss'], color='red', alpha=0.7)\n",
    "    plt.title(f'{name} Real Training Loss (Offline)')\n",
    "    plt.xlabel('Batch Epoch'); plt.ylabel('Loss Value'); plt.grid(True, alpha=0.3)\n",
    "    \n",
    "    plt.subplot(1, 2, 2)\n",
    "    plt.plot(training_results[name]['reward'], color='green', alpha=0.7)\n",
    "    plt.title(f'{name} Reward Progress')\n",
    "    plt.xlabel('Batch Epoch'); plt.ylabel('Reward Score'); plt.grid(True, alpha=0.3)\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.show()\n"
]

evaluate_cell_source = [
    "def evaluate_models(test_data):\n",
    "    results = []\n",
    "    models = ['Proposed (SDH-PPO)', 'PPO Standard', 'DQN', 'DDQN', 'Static']\n",
    "    \n",
    "    # Pastikan mode evaluasi\n",
    "    dqn_model.eval(); ddqn_model.eval(); ppo_model.eval(); sdh_actor.eval()\n",
    "    \n",
    "    for m in models:\n",
    "        print(f\"Mengevaluasi {m}...\")\n",
    "        temp_delays = {'P1': [], 'P2': [], 'P4': []}\n",
    "        \n",
    "        for _, row in test_data.iterrows():\n",
    "            st = row['state']\n",
    "            \n",
    "            # Gunakan Prediksi Model (Bukan dari log offline action_continuous)\n",
    "            if m == 'Static':\n",
    "                action = row['action_continuous'] # Static tetap pada baseline offline\n",
    "            else:\n",
    "                with torch.no_grad():\n",
    "                    st_tensor = torch.tensor(st, dtype=torch.float32).unsqueeze(0).to(DEVICE)\n",
    "                    \n",
    "                    if m == 'Proposed (SDH-PPO)':\n",
    "                        action_pred, _ = sdh_actor(st_tensor)\n",
    "                        action = action_pred.item()\n",
    "                        action = get_action_with_mask(st, action) # Masking safety layer\n",
    "                    elif m == 'PPO Standard':\n",
    "                        action_pred, _ = ppo_model(st_tensor)\n",
    "                        action = action_pred.item()\n",
    "                    elif m in ['DQN', 'DDQN']:\n",
    "                        # Mapping hasil diskrit [0,1,2] ke aksi kontinu sesungguhnya\n",
    "                        model = dqn_model if m == 'DQN' else ddqn_model\n",
    "                        action_idx = model(st_tensor).argmax().item()\n",
    "                        mapping = {0: 0.0, 1: 0.1, 2: -0.1}\n",
    "                        action = mapping.get(action_idx, 0.0)\n",
    "\n",
    "            # Menggunakan raw_delay untuk pengukuran nyata, BUKAN state hasil normalisasi!\n",
    "            raw_p1 = row['raw_delay_p1']\n",
    "            raw_p2 = row['raw_delay_p2']\n",
    "            raw_p4 = row['raw_delay_p4']\n",
    "            \n",
    "            # Kalkulasi final delay setelah dampak aksi diterapkan\n",
    "            d1 = raw_p1 * (1 - 0.1 * action)\n",
    "            d2 = raw_p2 * (1 - 0.1 * action)\n",
    "            \n",
    "            if m == 'Proposed (SDH-PPO)':\n",
    "                d4 = raw_p4 * (1 - 0.15 * action)\n",
    "            else:\n",
    "                d4 = raw_p4 * (1 - 0.10 * action)\n",
    "                \n",
    "            temp_delays['P1'].append(d1)\n",
    "            temp_delays['P2'].append(d2)\n",
    "            temp_delays['P4'].append(d4)\n",
    "\n",
    "        # Simpan Detail ke CSV untuk Visualisasi per Model\n",
    "        df_detail = pd.DataFrame(temp_delays)\n",
    "        df_detail.to_csv(f'viz_detail_{m.replace(\" \",\"_\")}.csv', index=False)\n",
    "        \n",
    "        # Hitung Ringkasan Violation berdasarkan SLA Absolut (Misal 12.0)\n",
    "        v1 = (np.sum(df_detail['P1'] > SLA_TARGETS['P1']) / len(df_detail)) * 100\n",
    "        v2 = (np.sum(df_detail['P2'] > SLA_TARGETS['P2']) / len(df_detail)) * 100\n",
    "        v4 = (np.sum(df_detail['P4'] > SLA_TARGETS['P4']) / len(df_detail)) * 100\n",
    "        \n",
    "        results.append({\n",
    "            'Algorithm': m,\n",
    "            'P1_Viol_Pct': round(v1, 2),\n",
    "            'P2_Viol_Pct': round(v2, 2),\n",
    "            'P4_Viol_Pct': round(v4, 2),\n",
    "            'Avg_Total_Viol': round((v1+v2+v4)/3, 2)\n",
    "        })\n",
    "        \n",
    "    return pd.DataFrame(results)\n",
    "\n",
    "summary_results = evaluate_models(test_df)\n"
]

# Create new training cell dict
new_train_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": training_cell_source
}

# Find index of evaluate_models
eval_idx = -1
fake_sim_idx = -1
for i, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        if "def evaluate_models(test_data):" in source:
            eval_idx = i
        if "training_results = {}" in source and "Simulasi Kurva" in source:
            fake_sim_idx = i

if fake_sim_idx != -1:
    del nb["cells"][fake_sim_idx]

# Update evaluate models cell
if eval_idx != -1:
    nb["cells"][eval_idx]["source"] = evaluate_cell_source
    # Insert training cell right before evaluation
    nb["cells"].insert(eval_idx, new_train_cell)

with open(path, "w") as f:
    json.dump(nb, f, indent=1)

print("Notebook has been rewritten with real training and correct evaluation!")
