"""LaTeX tables for the paper from the frozen V2 analysis. Formatting only, no statistic is recomputed.

    python scripts/paper_tables_v2.py

Reads results/analysis-v2/{primary,exploratory,secondary,fidelity_c4}.csv and writes
revisi/hasil-revisian/tables/v2_{cells,primary,exploratory,fidelity}.tex, which main.tex
pulls in with \\input. The .tex files analyze_v2.py writes itself carry Indonesian verdicts
and code names; these carry English labels, and every number is copied from the CSVs.
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ANA = ROOT / "results" / "analysis-v2"
OUT = ROOT / "revisi" / "hasil-revisian" / "tables"

METHOD = {"ppo": "PPO", "sdhppo": "SDH-PPO", "dqn": "DQN", "ddqn": "DDQN",
          "ressdhppo": "SDH-PPO residual", "bcsdhppo": "SDH-PPO + BC init",
          "demand_prop": "Demand Proportional", "no_control": "No Control",
          "equal_split": "Equal Split", "threshold": "Threshold"}
ARM = {"full": "real + synthetic", "real_only": "real only", "aug_subsample": "synthetic only",
       "no_dueling": "w/o dueling head"}
ORDER = ["ppo", "sdhppo", "dqn", "ddqn", "ressdhppo", "bcsdhppo",
         "demand_prop", "no_control", "equal_split", "threshold"]
VERDICT = {"X lebih baik": "X better", "X lebih buruk": "X worse", "tidak signifikan": "n.s."}


def ci(m, lo, hi):
    return f"{m:.2f} [{lo:.2f}, {hi:.2f}]"


def label(s):
    """'PPO [full] safety on' -> 'PPO, real + synthetic, safety on' (text from the CSV)."""
    name, rest = s.split(" [")
    arm, safety = rest.split("] ")
    return f"{METHOD.get(name, name)}, {ARM[arm]}, {safety}"


def table(env, caption, lab, cols, header, rows, note=None, fit=False):
    body = "\n".join(" & ".join(r) + r" \\" for r in rows)
    foot = f"\\\\[2pt]\n\\footnotesize{{{note}}}\n" if note else ""
    tab = (f"\\begin{{tabular}}{{{cols}}}\n\\toprule\n\\revhdr {header} \\\\\n\\midrule\n{body}\n"
           f"\\bottomrule\n\\end{{tabular}}")
    if fit:                                   # wider than the column: scale down to fit
        tab = f"\\resizebox{{\\linewidth}}{{!}}{{%\n{tab}}}"
    return (f"%% GENERATED by scripts/paper_tables_v2.py from results/analysis-v2. Do not edit.\n"
            f"\\begin{{{env}}}[t]\n\\centering\n\\caption{{{caption}}}\n\\label{{{lab}}}\n\\footnotesize\n"
            f"{tab}\n{foot}\\end{{{env}}}\n")


def cells():
    s = pd.read_csv(ANA / "secondary.csv")
    s[["method", "arm", "safety"]] = s.cell.str.extract(
        r"^(.+?)_(full|real_only|aug_subsample|no_dueling)_safety(on|off)$")
    s = s.assign(k=s.method.map(ORDER.index), a=s.arm.map(list(ARM).index)).sort_values(["k", "a", "safety"])
    rows = [[METHOD[r.method], ARM[r.arm], r.safety, str(r.n)]
            + [ci(r[f"viol_{p}"], r[f"viol_{p}_lo"], r[f"viol_{p}_hi"]) for p in ("p1", "p2", "p4", "total")]
            for _, r in s.iterrows()]
    return table("table*", "Violation Rate (\\%) per Configuration on the Test Split, Mean [95\\% Bootstrap CI] "
                 "Over Seeds. Lower Is Better", "tab:v2_cells", "lllrcccc",
                 "Method & Training data & Safety & $n$ & P1 & P2 & P4 & Total", rows)


def tests(csv, lab, caption, with_p):
    rows = []
    for _, r in pd.read_csv(ANA / csv).iterrows():
        row = [f"({r.family.replace('_safetyon', ', safety on')})", label(r.X), label(r.Y),
               ci(r.mean_d, r.ci_lo, r.ci_hi)]
        if with_p:
            row += [f"{r.p_holm:.3g}", f"{r.rank_biserial:.2f}",
                    next(v for k, v in VERDICT.items() if r.verdict.startswith(k))]
        rows.append(row)
    hdr = "Fam. & X & Y & $\\Delta$ [95\\% CI]" + (" & $p_{\\mathrm{Holm}}$ & $r_{rb}$ & Verdict" if with_p else "")
    return table("table*", caption, lab, "lllc" + ("rrl" if with_p else ""), hdr, rows, fit=True)


def fidelity():
    f = pd.read_csv(ANA / "fidelity_c4.csv")
    name = {"batas: riil-train vs riil-val": "real train vs real val (bound)",
            "sintetis vs riil-train": "synthetic vs real train"}
    ports = ["p1", "p2", "p4"]
    rows = [[name[r.perbandingan], r.slice.upper(), f"{r['KS D']:.3f}", f"{r['W1 (Mbps)']:.3f}",
             f"{r['|dACF| rata2 lag 1-10']:.3f}", f"{r['|dACF| maks lag 1-10']:.3f}"]
            for _, r in f[f.slice.isin(ports)].iterrows()]
    note = "; ".join(f"{name[r.perbandingan]}: AUC {r['AUC discriminator (5-fold)']:.3f} "
                     f"(fold s.d. {r['AUC sd antar fold']:.3f})" for _, r in f[~f.slice.isin(ports)].iterrows())
    return table("table", "Generator Fidelity Against the Intra-Dataset Bound (Train and Validation Only)",
                 "tab:v2_fidelity", "llcccc",
                 "Comparison & Slice & KS $D$ & $W_1$ (Mbps) & mean $|\\Delta\\mathrm{ACF}|$ & max $|\\Delta\\mathrm{ACF}|$",
                 rows, note="*Logistic-regression discriminator on 50x3 windows, 5-fold: " + note + ".", fit=True)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "v2_cells.tex": cells(),
        "v2_primary.tex": tests("primary.csv", "tab:v2_primary",
                                "Primary Comparisons of Total Violation Rate, Seed-Paired, Wilcoxon Signed-Rank "
                                "With Holm Correction Within Each Family. $\\Delta = X - Y$, Lower Is Better", True),
        "v2_exploratory.tex": tests("exploratory.csv", "tab:v2_exploratory",
                                    "Exploratory Comparisons of Total Violation Rate (No Significance Test). "
                                    "$\\Delta = X - Y$ With 95\\% Bootstrap CI", False),
        "v2_fidelity.tex": fidelity(),
    }
    for n, t in files.items():
        (OUT / n).write_text(t, encoding="utf-8")
    print(f"wrote {', '.join(files)} -> {OUT}")


if __name__ == "__main__":
    main()
